### ISSUE TITLE
Dropdown buttons turn black when active.

### ISSUE THREAD

**Issue by DirtDiglett** [DirtDiglett/Pressure2#1]
(Note: This is an example issue to demonstrate what a good issue report looks like)

When choosing an option from a dropdown button, the text of the button will turn from blue to black, which is inconsistent with other button behaviour.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA?

Yes.
#### A screenshot of the issue.

![issue1](https://cloud.githubusercontent.com/assets/3527401/13284539/9feb9a5e-db40-11e5-8038-0318e53b3e57.png)
#### Steps to reproduce the issue.

Open Steam Settings, navigate to Interface, and use any of the dropdown buttons that appear on this page.

**Comment by Asphira** [comment]
I know this is going to remain as a example issue, but do have an easy fix,

 In control.styles add selectedtextcolor=blue500 into the Combobox area, aka mine is now

```
    ComboBox {
        textcolor=blue500
        selectedtextcolor=blue500
                    etc etc
```

}

**Comment by DirtDiglett** [comment]
You're a beautiful human Asphira.
