### ISSUE TITLE
Nicknames are difficult to see in chat windows

### ISSUE THREAD

**Issue by wu4** [DirtDiglett/Pressure2#10]
In chat windows and on the friends list, nicknames show up black. For the former, this doesn't seem to be intended behavior:

![Nicknames not showing up properly](https://cloud.githubusercontent.com/assets/10952527/13289865/87e67124-dadf-11e5-9646-c5dca4314717.png)

Currently using the Steam Beta.

**Comment by Js41637** [comment]
Weird they're grey for me. From the image your 'colors' seem to be very bright, or at least brighter than they appear for me.

**Comment by DirtDiglett** [comment]
Oddly they seem to be significantly darker for you than they appear for me, but I think I may know why.

I will look into getting this visibility improved.
