### ISSUE TITLE
Local streaming parameters

### ISSUE THREAD

**Issue by Leeo97one** [DirtDiglett/Pressure2#100]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2

#### Description of the issue.
The local streaming parameters are really buggy, especially in the advanced options.

#### Does it also occur on Steam without the skin installed?
Fortunately not.

#### Are you in the Steam BETA?
Nop.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
`Linux leeo-arch-pc 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux`

#### Are you using the latest stable release or using the latest commit version?
Latest stable release (1.0.4)

#### A screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/1344241/26765885/d2cdda90-4985-11e7-99b1-a0f173efd364.png)

#### Steps to reproduce the issue.
Install Pressure² and go to the local streaming parameters.

**Comment by DirtDiglett** [comment]
Fixed in soon-to-be-released 1.1
