### ISSUE TITLE
Pressure2 Dark-Find command wrong color

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#101]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2-Dark

#### Description of the issue.
When trying to use the find command (CTRL+F), about half of the bar will be white instead of black. 

#### Does it also occur on Steam without the skin installed?
No.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Latest stable release, 1.0.0

#### A screenshot of the issue.
https://i.imgur.com/fcN3bFU.png

#### Steps to reproduce the issue.
Use CTRL+F on a page that isn't the steam library.

**Comment by DoctorDinosaur** [comment]
Fixed in my unofficial patch: https://github.com/CptDinosaur/Pressure2DarkPatch

**Comment by DirtDiglett** [comment]
No longer an issue in Pressure 1.1
