### ISSUE TITLE
I can't write on the custom box when backup games.

### ISSUE THREAD

**Issue by BanCrash** [DirtDiglett/Pressure2#104]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
When I tried to make a game backup, if I choose custom size option I can't write on the box, because if I pulse that box it shows again the menu, not letting me write on that box.

#### Does it also occur on Steam without the skin installed?
No, without the skin this works correctly.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I am on the last release of Steam. I tried to enter the BETA to check if that happens too and it does. So this happens on last release and last beta.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10.

#### Are you using the latest stable release or using the latest commit version?
I am using the latest commit version of Dark Mode.

#### A screenshot of the issue.
![image](https://user-images.githubusercontent.com/11770760/27869842-784bd386-61a1-11e7-863f-746863884cac.png)

![image](https://user-images.githubusercontent.com/11770760/27869855-80bdfe2c-61a1-11e7-87a2-94128507f12f.png)

#### Steps to reproduce the issue.
Right click on a game -> select Backup Game files -> Next -> Next -> select on the file size menu Custom and try to write on the box.

**Comment by DirtDiglett** [comment]
Fixed this for 1.1 release.

**Comment by BanCrash** [comment]
Perfect, thanks!
