### ISSUE TITLE
I can't view the final category of games in detailed view

### ISSUE THREAD

**Issue by BanCrash** [DirtDiglett/Pressure2#105]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
When I set the view to detail view mode, If I scroll to the low I can't see the last category properly. If matter, I have enabled show game icons.

#### Does it also occur on Steam without the skin installed?
No, without the skin this doesn't happen.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I am on the last release of Steam. I tried to enter the BETA to check if that happens too and it does. So this happens on last release and last beta.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10.

#### Are you using the latest stable release or using the latest commit version?
I am using the latest commit version of Dark Mode.

#### A screenshot of the issue.
The last category is VR, however it doesn't show properly.

![image](https://user-images.githubusercontent.com/11770760/27870149-697bbd98-61a2-11e7-8c3d-166cad2c0129.png)

By the way, this doesn't happen on list view mode:

![image](https://user-images.githubusercontent.com/11770760/27870319-db986cb4-61a2-11e7-8872-0ad29a784d04.png)

#### Steps to reproduce the issue.
Scroll to the low on the game list in detail view mode.

**Comment by DirtDiglett** [comment]
Unfortunately I can't fix this. The way Valve have it calculating the height of the list container is a bit awkward and seems to not handle extra heights added via `minimum-height`. Despite numerous attempts to solve it I can't seem to hack it together to work.

**Comment by BanCrash** [comment]
Well, thanks for trying it, I appreciate it.
