### ISSUE TITLE
Various formatting anomalies

### ISSUE THREAD

**Issue by wu4** [DirtDiglett/Pressure2#11]
Lumped together into a single issue since they'll all likely be fixed in the same revision. Tossing a checklist in for convenience.

Using the Steam Beta.
- [x] The "Set Taskbar Preferences" button under Interface clips with its surroundings. Looks like its position is defaulting to the top-left:

![anomaly1](https://cloud.githubusercontent.com/assets/10952527/13290933/c33c65ae-dae3-11e5-97d6-95c0386e0a53.png)
- [ ] Word wrapping seems to kill the look of checkbox text:

![anomaly2](https://cloud.githubusercontent.com/assets/10952527/13290968/f0f1a8ba-dae3-11e5-8d70-cd78546396db.png)
- [x] No text at all under Broadcasting:

![anomaly3](https://cloud.githubusercontent.com/assets/10952527/13290973/fe4edc30-dae3-11e5-8450-3f5bd44daa93.png)
- [x] The Search bar in the upper left is slightly longer than the games list when using the Details view:

![anomaly4](https://cloud.githubusercontent.com/assets/10952527/13291007/1dc2fb5a-dae4-11e5-9624-ff944b2eb3b3.png)
- [x] The Wallet balance interferes with the Store's dropdown:

![anomaly5](https://cloud.githubusercontent.com/assets/10952527/13291026/3e0e1480-dae4-11e5-932a-b8ac8a37e6a5.gif)

It should probably be moved, despite the nice placement. #5

**Comment by Js41637** [comment]
I don't know why most of this is happening for you, especially the settings glitches, I don't have them at all although it is clear most of these issues are because of the larger than _normal_ font size. 

Could you try redownloading the skin?

**Comment by wu4** [comment]
> I don't know why most of this is happening for you, especially the settings glitches, I don't have them at all although it is clear most of these issues are because of the larger than _normal_ font size. 
> 
> Could you try redownloading the skin?

Sorry, I forgot to add that I'm on Linux. That might be the issue. I'll
redownload just to be sure.

**Comment by Js41637** [comment]
OHHHHH well Linux does have larger than normal fonts. It is a bit hard to edit for OSX and Linux because they can be hard to test and need special styles. It is possible that they are broken for Linux andor Mac.

**Comment by DirtDiglett** [comment]
Hi @wu4 and thanks for the detailed report. I've got no nix box available to test with, but was kind of hoping for the best that things wouldn't be too broken in it, which from your screenshots it appears most things worked fine.

For the "Set Taskbar Preferences" button under Interface, this was caused because I told it to start at the checkbox for hardware acceleration, forgetting that this checkbox only appears on Windows. This is an easy fix that I've just commited to the repo.

I'll look at getting these all fixed for a 1.0.1 release.

**Comment by wu4** [comment]
@DirtDiglett That's unfortunate. I didn't know Linux/Mac Steam was so inconsistent. I'll be sure to keep you up to date on any other things I come across, then.

**Comment by DirtDiglett** [comment]
@wu4 Do you get broadcast options in Settings when you're using default Steam's theme on Linux?

**Comment by wu4** [comment]
@DirtDiglett Actually, no. I get the following:

![Steam Broadcasting is not supported in your operating system](https://cloud.githubusercontent.com/assets/10952527/13329569/96028d36-dbc2-11e5-9c18-46a18977e568.png)

**Comment by DirtDiglett** [comment]
Hey @wu4 can you try the latest commit under the development branch and confirm that the Search bar is sorted, and that under Broadcasting Settings it now shows the disabled label correctly with the URL underneath?

https://github.com/DirtDiglett/Pressure2/tree/development

**Comment by wu4** [comment]
@DirtDiglett Hey, sorry. For some reason this issue no longer gives me emails, so I have to manually check every now and then. Looks like its width is too small:
![Broadcasting width](https://cloud.githubusercontent.com/assets/10952527/13375145/23aeb746-dd66-11e5-9209-bd5b50bc6700.png)

**Comment by DirtDiglett** [comment]
Can you give it another try from the development branch, I've added a max width that should sort it out.

**Comment by wu4** [comment]
Works!

![sat feb 27 22 28 36 est 2016 window screen](https://cloud.githubusercontent.com/assets/10952527/13377264/7497cfae-dda1-11e5-94c6-a7b2d96d01d0.png)
