### ISSUE TITLE
Unable to search games when you have an account alert

### ISSUE THREAD

**Issue by DragonHeart000** [DirtDiglett/Pressure2#110]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
When you have an account alert and do not close it out, since I like to keep them. You are unable to search your steam library since the area to click on the account alert bar seems to stretch out and over the search bar. 

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Still happens.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Stable

#### A screenshot of the issue.
https://i.gyazo.com/813519888d19d23c4d751434c41377bd.mp4

#### Steps to reproduce the issue.

1. You must have an account alert at the time. (Mine was with a game being removed from my library but this could be a lot of different things)

2. Leave the account alert up and go to your library.

3. Try clicking on the search box for your library and the account alert will prevent you from doing so.

**Comment by DirtDiglett** [comment]
> since I like to keep them.

What. Why?

I think this is fixed in 1.1, can't test or confirm due to not having any alerts.

¯\\\_(ツ)\_/¯
