### ISSUE TITLE
Variable window size

### ISSUE THREAD

**Issue by Metazolid** [DirtDiglett/Pressure2#111]
Im using Pressure2 with a modified chatfont size.

Not an actual issue, merely a question, if there is a way to set specific values for newly opened windows like the chat, or the friends list in order to have all newly opened windows in a organized size and position.
They're somwhere in the middle and at a relatively small size by default and would like to change the corresponding values somehow.

It's a Steamthing I guess, so it basically affects all skins.

I am in Steam Beta.

Win 7

Currently using Pressure 1.0.1

https://i.imgur.com/S6U6NTY.png

**Comment by DirtDiglett** [comment]
The only way I can think of would be to hard-apply a `minimum-height` and `minimum-width` to `CChatRoomDlg` and `CChatRoomDlg` to prevent it from shrinking any smaller... but if the size Steam 'remembers' is bigger than that, it'll not work, but it will prevent the window from going any smaller.

You can't modify the default position though.
