### ISSUE TITLE
Colours of game name in library are completely invisible while the image is loading

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#112]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2

#### Description of the issue.
Basically the title of the game, will not appear during the loading of the image. Due to both the place-holder and the text colour being white. My only thought would be to change the place-holder white background with something darker.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Not in Beta

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Ubuntu 17.10 with Arc Darker GTK and Arc shell theme.

#### Are you using the latest stable release or using the latest commit version?
Stable

#### A screenshot of the issue.
**BEFORE LOAD**
![screenshot from 2017-11-25 18-32-46](https://user-images.githubusercontent.com/22744080/33228909-88823796-d1bc-11e7-8613-aa8f8bccc63e.png)

**AFTER LOAD**
![screenshot from 2017-11-25 18-32-48](https://user-images.githubusercontent.com/22744080/33228912-8e57d806-d1bc-11e7-9202-931ac84b680c.png)

**Comment by DirtDiglett** [comment]
I have spent absolutely forever trying to get this fixed in some manner or another, and have never had any success. I give up, it's staying broken sorry. I have tried every trick, every hacky workaround, every solution I can come up with and no matter how I tackle it... it's just not fixable.
