### ISSUE TITLE
Give Pressure a licence

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#113]
I would highly suggest licensing Pressure. This allows users to know their rights.

https://choosealicense.com/

Is a very handy site for deciding.

**Comment by ghost** [comment]
Whoops didn't see the Licence file :face_with_head_bandage:

I know that Github lets you set one that shows on the whole project though, So I would suggest setting that.

**Comment by thornjad** [comment]
To get GitHub to recognize it, Pressure needs to use a recognized license. The CCPL it has right now is not designed for software. I would highly recommend the ISC or MIT licenses.

Also it should be renamed to LICENSE.

**Comment by DirtDiglett** [comment]
Yeah GitHub doesn't like me using CCPL. It was the only one that seemed to cover what I wanted to allow/disallow with the license.

Basically, I don't care if you make derivatives or offshoots or whatever, make it better, worse, whatever. Just don't try to make money off of Pressure² and give me credit...
