### ISSUE TITLE
Fonts issues (only bugged in beta) and steam wallet funds misplacement [MAC]

### ISSUE THREAD

**Issue by BepisR47** [DirtDiglett/Pressure2#114]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2

#### Description of the issue.
The fonts on mac seem to not work correctly (the titles like the ones in the "store" and "library" bar actually DO work) even after various installations/restarts of the steam app, the steam wallet funds number is also displayed over said title bar, when in the screenshots it is placed under.

#### Does it also occur on Steam without the skin installed?

Nope and not really since the number on the vanilla skin is normally at the left of the main steam window and it works fine on old pressure for steam 1.0.9

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

I was in the beta, when opting out of the beta the fonts were repaired but the steam wallet funds were still broken

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

OSX El capitan 10.11.6

#### Are you using the latest stable release or using the latest commit version?

latest stable release

**Comment by DirtDiglett** [comment]
Should be fixed in Pressure 1.1
