### ISSUE TITLE
Pressure2 Dark Error 1-operation not permitted.

### ISSUE THREAD

**Issue by Reden1039** [DirtDiglett/Pressure2#115]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark
#### Description of the issue.
Whenever I install and open the app, an error window opens and says "Unable to expand "Pressure2-Dark-1.0.zip" into "Desktop"."
(Error 1-Operation Not Permitted).
When I download the regular Pressure2, it opens up fine and it successfully opens as the steam skin.
#### Does it also occur on Steam without the skin installed?
x
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
no.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Mac OSX 11.1
#### Are you using the latest stable release or using the latest commit version?
I am using the version that is up on the Pressureforsteam
#### A screenshot of the issue.
<img width="380" alt="screen shot 2017-12-04 at 10 28 46 pm" src="https://user-images.githubusercontent.com/34259523/33588756-8581611a-d942-11e7-8a05-1f4c46b8a010.png">

#### Steps to reproduce the issue.
Download the Pressure2 Dark skin from http://pressureforsteam.com/, open app.

**Comment by Js41637** [comment]
Sorry that you've having issues unfortunately there has been a history of problems happening for macs however we are unable to look into the issue as neither Dirt or I have a mac available for testing.

What you can try however is downloading the repo directly via Github which you can do by clicking `Clone or Download` on the main repo page and clicking download as Zip and try using that one.

![image](https://user-images.githubusercontent.com/6258213/33801557-d7a55202-ddb2-11e7-8bbd-bc4df3155250.png)
