### ISSUE TITLE
Pressure2Dark Incorrectly displaying menu items.

### ISSUE THREAD

**Issue by HeySteets** [DirtDiglett/Pressure2#116]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2Dark

#### Description of the issue.
When Igo into certain menus, namely the menus concewrning game file storage, the 'Move Install Folder' button is off to the left, out of line with all the others.

#### Does it also occur on Steam without the skin installed?
No. It doesn't occure on Pressure 2 Light either.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No. No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Windows 10 Insider.

#### A screenshot of the issue.
The first is of the issue. The second is what it should look like.
[https://imgur.com/a/ZwKEr](https://imgur.com/a/ZwKEr)
#### Steps to reproduce the issue.
Open Steam>Go to a game>Right click>Properties>Local FIles (There it is.)

**Comment by DoctorDinosaur** [comment]
Fixed in my unofficial patch: https://github.com/CptDinosaur/Pressure2DarkPatch

**Comment by DirtDiglett** [comment]
Closing, this is fixed for Pressure 1.1
