### ISSUE TITLE
Installation instructions for Mac OS name incorrect location for 10.13.x installs

### ISSUE THREAD

**Issue by czamp** [DirtDiglett/Pressure2#117]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2

#### Description of the issue.
Installing Pressure2 to `Applications/Steam.app/Contents/MacOS/skins` does not cause the Pressure2 skin to appear in the Interface > Skin Selection menu in Steam.

#### Does it also occur on Steam without the skin installed?
N/A

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Issue occurred whether Beta was opted in, or opted out.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Mac OS 10.13.1

#### Are you using the latest stable release or using the latest commit version?
1.0.4 stable

#### Steps to reproduce the issue.
1. Run Mac OS 10.13.x
2. Follow installation instructions

#### Proposed Fix
Update the Mac installation instructions to include the correct path for installing Steam skins when user is running the latest Mac OS

The correct installation path is:

`~/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/skins`

**Comment by DirtDiglett** [comment]
Looks like it's a different install path depending on OS X version.

I've modified the readme.md on my 1.1 branch to include both versions, will come in with the 1.1 release and will modify the website as well.
