### ISSUE TITLE
[Pressure2 Dark] Text Error on the Updating Games Screen

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#118]
#### Are you using Pressure2 or Pressure2 Dark?

Pressure2 Dark

#### Description of the issue.

Display of the updating game screen text out of whack.

#### Does it also occur on Steam without the skin installed?

No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10 64-bit

#### Are you using the latest stable release or using the latest commit version?

Yes

#### A screenshot of the issue.

![pressure-2-dark-bug](https://user-images.githubusercontent.com/23663019/34471878-ef6b0cbc-ef21-11e7-920b-dcce6aebaff2.png)

#### Steps to reproduce the issue.

Start a game download, press play, it will bring up this screen until the game has been downloaded.

**Comment by DoctorDinosaur** [comment]
Fixed in my unofficial patch: https://github.com/CptDinosaur/Pressure2DarkPatch

**Comment by DirtDiglett** [comment]
Duplicate of #99
