### ISSUE TITLE
Friends bug

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#119]
#### Are you using Pressure2 or Pressure2 Dark?
Im using Pressure2 Dark

#### Description of the issue.
When Im in friends, and I drag down or up its hanging

#### Does it also occur on Steam without the skin installed?
no

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Im not in beta

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Latest Dark version

#### A screenshot of the issue.
![ekran goruntusu 6](https://user-images.githubusercontent.com/29867363/35766912-0b83cef4-08f2-11e8-8088-57650e6aa1f7.png)

**Comment by Js41637** [comment]
Yeah sorry, this is a known issue that seems to only occur for some people. I and the other developers are not able to reproduce it. The skin does use some fancy stuff and hacks which might be the cause but I suspect it is just related to PC performance.

Sorry, there is nothing we can do.
