### ISSUE TITLE
[In-Game Overlay] Missing Text

### ISSUE THREAD

**Issue by Hatomike** [DirtDiglett/Pressure2#12]
**Does it also occur on Steam without the skin installed?**
No.

**Are you in the Steam BETA?**
No.

**Screenshots of the issue:**
- [x] [In game overlay](http://i.imgur.com/GQbTGgA.jpg)
  -Blue links don't exist.
  -Time don't show up.
  -When you have all achievements, the "so close" one disappear and left an empty gap.
- [x] [Friend button](http://i.imgur.com/988471q.jpg)
  -Is way too bigger than the clickable area. (This is the maximum I get with my cursor before going into the clickable area)
- [x] [Wallet amount](http://i.imgur.com/QQ06SFG.jpg)
  -Isn't centered.
  -(Also I don't think it should be here, but that's my personal opinion)
- [x] [Friend offline](http://i.imgur.com/Dq48YeN.jpg)
  -Little visual glitch.
  -(I miss that little arrow for switching between "online" and others, still personal opinion tho.)

Also, there is a lots of text that doesn't fit the window but this isn't a major issue for the moment.

**Comment by DirtDiglett** [comment]
Hi @Hatomike and thanks for your report,

I'll look into getting these sorted out as part of 1.0.1 bugfix update. I'm pretty sure by looking at your screenshots that you have, but you did install the Roboto fonts included in the skin right? I ask because it's really odd for the text to just... vanish. Roboto has full support for french accents so that shouldn't be the cause but I'll investigate further.

The Wallet amount issues is the same issue reported in #5 and is being worked on.

The Friends Offline issue is the same issue reported in #2 and is being worked on.

**Comment by Hatomike** [comment]
I'm using Roboto everyday for different projects and I re install it from your folder every time a pressure update come out (and all other fonts as well).
The game resolution was 1920x1080.
I didn't test on others games but I can if needed.

**Comment by DirtDiglett** [comment]
Thanks for the confirmation @Hatomike, I'll try to reproduce the issues myself when I am at my dev machine tonight.

**Comment by Hatomike** [comment]
@DirtDiglett 
Update:
-In english, the text vanish too, this doesn't seems to be because of the french interface.
-Installing Roboto fonts and the theme itself again don't fix the issue.
-The resolution and the game have nothing to do with it. (Tested with multiple games and resolution)

**Comment by DirtDiglett** [comment]
That's strange, I've just seen a screenshot from another individual that also experiences the same issue.

Do you use Family View or anything similar? Is the game being streamed or is it local to the machine?

**Comment by Hatomike** [comment]
I don't use Family View, my game isn't being streamed.
I'm playing on local.

I've tried launching steam in english with "Local Emulation" since my computer is in french, still nothing.

Maybe this could be fixed with a reboot but I can't test this now.

**Comment by Hatomike** [comment]
Reboot doesn't fix anything.
My friend have the same issue and don't know why either.
New not major issue on windowed games with a little resolution: Last links on the left get under the achievements zone.

[Screenshot](http://i.imgur.com/MV5ILD2.jpg)
EDIT: #21

**Comment by DirtDiglett** [comment]
Hey @Hatomike can you confirm something for me. If you uncheck "Enable DirectWrite for improved font smoothing and kerning" under Steam Settings > Interface, then restart Steam does the vanishing text reappear?

**Comment by Asphira** [comment]
Oddly enough when tinkering away, DirectWrite seems to somewhat be the cause, but only with the bold font itself (Roboto Bold), when i changed as a test Roboto Bold simply back to Roboto I was able to continue using DirectWrite, wierdest part to top it off, this seems to only effect a small number of users including myself, on various different os's, configurations and the font working perfectly elsewhere.

What would happen Dirt, if you replaced use of the bold in the overlay, but add font-weight to beef it up to bold it? That hopefully would a) still keep it looking bold and b) allow the use of DirectWrite and having the font be bold in areas that work no issue for all

**Comment by Hatomike** [comment]
@DirtDiglett 
Without DirectWrite the text is here.
I have nothing more to add to what @Asphira have said.

**Comment by DirtDiglett** [comment]
Can you please try this version of the skin from the development branch, this should resolve the issues but I want to be certain before pulling into the main branch.

https://github.com/DirtDiglett/Pressure2/archive/development.zip

**Comment by Hatomike** [comment]
Work like a charm !
Nothing more to say !
