### ISSUE TITLE
Button to open up SteamVR is missing.

### ISSUE THREAD

**Issue by StefanoFiumara** [DirtDiglett/Pressure2#120]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
I am unable to find a button on the UI to start up Steam VR so I can use my HTC Vive.

#### Does it also occur on Steam without the skin installed?
The default Steam Skin provides a button in the top right corner of the screen (next to the big picture button)
![image](https://user-images.githubusercontent.com/2746784/39222012-d6d89836-47ff-11e8-93b7-0642ad2fe256.png)

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Not in the Steam Beta.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10.

#### Are you using the latest stable release or using the latest commit version?
Latest stable.

**Comment by DirtDiglett** [comment]
I've added it to the menu for the next release shortly.
