### ISSUE TITLE
[Issue] Displaying error on Settings

### ISSUE THREAD

**Issue by jks15satoshi** [DirtDiglett/Pressure2#121]
#### Are you using Pressure2 or Pressure2 Dark?
Using Pressure2 Dark currently.

#### Description of the issue.
Text overlay occurs on Settings.

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10, version 1803

#### Are you using the latest stable release or using the latest commit version?
Latest stable release

#### A screenshot of the issue.
![tim 20180609122520](https://user-images.githubusercontent.com/27013554/41187631-38926012-6be0-11e8-9fc9-1f7fe6b1ac91.png)
_Text issue on Friends tab_

![tim 20180609120737](https://user-images.githubusercontent.com/27013554/41187593-6cfd7a22-6bdf-11e8-8111-485dc6be1c88.png)
_Text issue on Interface tab_

**Comment by DirtDiglett** [comment]
Fixed for 1.1 release
