### ISSUE TITLE
[Suggestion] Suggestion about the download page

### ISSUE THREAD

**Issue by jks15satoshi** [DirtDiglett/Pressure2#122]
#### Are you using Pressure2 or Pressure2 Dark?
Using Pressure2 Dark currently.

#### Description of the issue.
It's better to add a transparent background on the back of the download status, or separate it from the graph. The graph makes the download status uncomfortable to view.

#### Does it also occur on Steam without the skin installed?
No.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10, version 1803

#### Are you using the latest stable release or using the latest commit version?
Latest stable release

#### A screenshot of the issue.
![tim 20180609120606](https://user-images.githubusercontent.com/27013554/41187697-28e1c138-6be2-11e8-80e6-9ededcf79334.png)

**Comment by DirtDiglett** [comment]
I've fixed this for versions 1.1, the graph now fades out nicely.
