### ISSUE TITLE
Steam Pressure 2 Dark Skin in Spanish Bug

### ISSUE THREAD

**Issue by MrHomunculus** [DirtDiglett/Pressure2#123]
#### **A screenshot of the issue.** The top part of the login the "Steam" square, is not complete. 

![image](https://user-images.githubusercontent.com/24828449/41191573-f7effc7e-6bf1-11e8-9093-46e5b9649578.png)

**And the descripton text of Steam Guard confirmation is very simple and it does not look very good**

![image](https://user-images.githubusercontent.com/24828449/41191650-0d71836e-6bf3-11e8-8368-e5ba433aaa80.png)

#### Steps to reproduce the issue.

Start Steam whit Pressure2 Dark Skin in Spanish Lenguage (The issue is in the login skin)

**Comment by DirtDiglett** [comment]
Fixed for the upcoming 1.1 release

**Comment by MrHomunculus** [comment]
😊👍👌
