### ISSUE TITLE
[FIX] Unofficial Patch for Pressure 2 v1.0.4 and Pressure 2 Dark v1.0 to work with the new Steam UI and chat

### ISSUE THREAD

**Issue by leyyce** [DirtDiglett/Pressure2#125]
### [FIX] Unofficial Patch for Pressure 2 v1.0.4 - Steam Chat Beta Update
![Main Window](https://i.imgur.com/RhxwGK7.jpg)

This is an unofficial patch I made to make Pressure 2 work with the recent steam client beta update.
**If you want your skin to be completely functional use Pressure 2 Dark for now (the dark version is more fitting for the new chat design anyways)**

_**Edit 25.07.2018:
Because I saw that @DirtDiglett was actively working on a new Pressure 2 Version that will fix the issues with the new UI I wasn't continuing to work on the Light Version of my fix but because his last commit was over 2 weeks ago I will look into fixing the light version tomorrow so that you can keep using Pressure 2 until the official fix arrives.**_

_**Edit 31.07.2018:
Because I was busy with other things in the last few days I couldn't finish the light skin although I was really hoping to be able to. I'm sorry and hope I will find time in the next few days.**_

**Pressure 2 Dark [Patch Version 1.3]**
At the moment everything in Pressure 2 Dark should be working fine but if you do find a bug please let me know here or on [this](https://steamcommunity.com/groups/pressureskin/discussions/0/3051633726576849955/) post in the Pressure Steam group and I will do my best to fix it but I can not promise anything because I have no other prior in steam theming.
 
**Pressure 2 Light [Patch Version 1.1]**
In the light skin everything is working fine except the dropdown menu under the account button. I will fix this in the next days when I find time because I need to change some colors.
  

I also need a more fitting icon for the new announcement button in the main interface. For now I used the icon of the original steam client release.

#### Pressure Dark
v1.3
>The notification button was overlapping with some other ui elements when it was active. I changed it to fit in the new ui.
>![Fixed Nofitication Icon](https://i.imgur.com/GCObKXV.jpg)

**Download**
> [Pressure2_Dark-Chat-Beta-Fix-v1.3.rar](https://elcapitan.io/downloads/Pressure2_Dark-Chat-Beta-Fix-v1.3.rar)  [[VirusTotal]](https://www.virustotal.com/#/file/f3b4d397a8c6ef8a3c7e77d0b8fa0091056ac52ff88caeee8eed64d042dac4a9/detection)
>[Pressure2-Chat-Beta-Fix-v1.1.rar](https://elcapitan.io/downloads/Pressure2-Chat-Beta-Fix-v1.1.rar)  [[VirusTotal]](https://www.virustotal.com/#/file/f1424deedd7c69a96712678efc26f90d6ff79bcc53c2331e5229ee1d63a35e61/detection)

**Comment by SauDough** [comment]
Thanks!

**Comment by C1oudust** [comment]
Thanks!

**Comment by deuxdoom** [comment]
thx for patch !

**Comment by CrazyCookies** [comment]
Thanks dude!!!

**Comment by ghost** [comment]
This is literally a lifesaver for me; I don't know what I would do if I went back to the default Steam skin.
Thank you *so much*.

**Comment by BlagoYar** [comment]
Thanks!
