### ISSUE TITLE
Text is fuzzy in the in game friends list

### ISSUE THREAD

**Issue by Anidion** [DirtDiglett/Pressure2#13]
[Screenshot](http://i.imgur.com/ulJxPaB.jpg)
Steam Beta:
Not Installed
Happens in default skin?:
No
Steps to reproduce:
Open the steam community (shift+tab) inside a game and open the friends list.

**Comment by katanacrimson** [comment]
Do you have DirectWrite enabled in steam (interface tab of settings)?  What OS?

**Comment by DirtDiglett** [comment]
As @damianb has queried, can you please provide me with what your operating system is (Windows, Mac OSX, Linux, etc.) and if you use Windows, please try it both enabled and disabled with DirectWrite in settings and let me know the results.

**Comment by ghost** [comment]
@DirtDiglett I actually have the exact same issue as @Anidion.

I have tried with DirectWrite turned on & off and it just looks a lot worse if it's turned off. (as shown in his screenshot)

I'm on Windows 10 Pro 64-bit

If you need i can take screenshots of how it looks with directwrite on/off.

**Comment by Anidion** [comment]
Running Windows 10 Pro 64bit, looks the same with or without DirectWrite and with hardware video decoding.

**Comment by roknir** [comment]
I have this problem too on Windows 7 (64-bit), same with DirectWrite on or off, though more text around it looks worse with it off, in my opinion (probably expected).
Playing around with this a bit, it seems like it's text that is bolded that's the problem.  Bolded text in the friends list for friends in-game, online, or offline all looks bad.  Inside of an IM window to a specific friend, the bolded "Never tell your password to anyone." at the top looks bad, but the non-bolded IM chat looks fine.

**Comment by Asphira** [comment]
I recall it is mostly because overlay does not seem to use Direct Write correctly / has a dodgy method for it for performance sake, if only when in overlay it was possible to just tell steam to not use the bold fonts (Pretty certain even if we use the base non bold font and beef up its font-weight to create a boldness it still looks bad) I will look into it a little for dirt
