### ISSUE TITLE
White background when viewing downloading games from the downloads tab.

### ISSUE THREAD

**Issue by Klasc-tech** [DirtDiglett/Pressure2#131]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure 2 Dark

#### Description of the issue.
Downloads tab has white background of games being downloaded

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No. 

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Yes

#### A screenshot of the issue.
![capture](https://user-images.githubusercontent.com/40745390/44240051-e636bc00-a181-11e8-86eb-c535f54a6070.JPG)

#### Steps to reproduce the issue.

Just installing the skin and restarting steam.

**Comment by thakyZ** [comment]
Not to mention the titles of each collapsable area is white too, and the text color for the play button is not colored right
![image](https://user-images.githubusercontent.com/950594/44240488-35292500-a173-11e8-8cab-bf1986247cc4.png)
