### ISSUE TITLE
Friend List and Chat Visual Glitch

### ISSUE THREAD

**Issue by vsilvar** [DirtDiglett/Pressure2#14]
Same as the previous bug in Pressure:
https://github.com/DirtDiglett/Pressure-for-Steam/issues/376

**Comment by DirtDiglett** [comment]
Can you please provide me with screenshots of it in Pressure², as from what I understand the code is in Pressure² to support this fine already.

**Comment by vsilvar** [comment]
![Language Bar](http://i.imgur.com/5c7it6a.png)
