### ISSUE TITLE
No music player button in Overlay

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure2#15]
http://steamcommunity.com/groups/pressureskin/discussions/0/405692758702677521/

**Comment by DirtDiglett** [comment]
All the code is there for it to appear, so I'll have a bit of an investigation as to why it doesn't appear and try to get it fixed for 1.0.1

**Comment by DirtDiglett** [comment]
Is it not here? I've just tested and confirmed it appears for me.

![invisible](https://cloud.githubusercontent.com/assets/3527401/13313580/d4269a9e-dbea-11e5-9d4b-c3fb6c0afc92.PNG)

**Comment by Js41637** [comment]
:))
