### ISSUE TITLE
OS X: Filters for installed/recent/all games in library looks a bit odd

### ISSUE THREAD

**Issue by jessb321** [DirtDiglett/Pressure2#16]
I haven't tested it on windows yet, but the font looks a bit weird under OS X. I have checked and made sure that the fonts are all installed. The currently selected one at the top looks fine, but the ones below look odd to me. Can anyone on windows confirm that it looks a bit odd?
<img width="179" alt="screen shot 2016-02-25 at 11 14 33 am" src="https://cloud.githubusercontent.com/assets/9222609/13305698/600f37da-dbb1-11e5-9cf1-d894089a3f09.png">

**Comment by DirtDiglett** [comment]
Windows, OSX, and Linux have completely different font rendering engines, which is why it looks different from the screenshots I have from my Windows machine.
