### ISSUE TITLE
Friends list difficult to read as "offline"

### ISSUE THREAD

**Issue by katanacrimson** [DirtDiglett/Pressure2#2]
As on tin.  Screenshot for you: 

![Friends list while offline](http://i.imgur.com/SDMJ8EV.png)

Steam beta.  Just go offline to repro, no need to start steam in offline mode. Though, that probably should be checked too.

**Comment by katanacrimson** [comment]
Offline mode isn't the best either, it's black on gray text as well.

![Friends list in offline mode](http://i.imgur.com/WG6jJbr.png)

**Comment by DirtDiglett** [comment]
Thanks for the report, I'll look into getting this fixed for the Bugfix update.
