### ISSUE TITLE
Message notification text is black

### ISSUE THREAD

**Issue by skittoh** [DirtDiglett/Pressure2#20]
When you receive a message notification the text is black and it makes it hard to read.

**Does it also occur on Steam without the skin installed?**
No.

**Are you in Steam BETA?**
No.

**A screenshot of the issue.**
![untitled-1](https://cloud.githubusercontent.com/assets/17479017/13326684/afcf38ec-dbc5-11e5-892f-dd2248f590e0.png)

**Comment by Wiggin38** [comment]
Can confirm I have this issue as well.
