### ISSUE TITLE
In-game overlay bug

### ISSUE THREAD

**Issue by leyyce** [DirtDiglett/Pressure2#21]
**Does it also occur on Steam without the skin installed?**
No.

**Are you in the Steam BETA?**
Yes.

After the overlay problem from Issue #4 are fixed I have to report a new overlay bug (1366x768 res). I hope the screenshot I'm providing will be enough to describe the bug.
![tf2_1366x768](https://cloud.githubusercontent.com/assets/13371024/13332906/75c0da68-dc04-11e5-9d92-a9605f9fd4a8.jpg)

**Comment by DirtDiglett** [comment]
Ok, so what do you want to happen here? You're using a tiny resolution (Remember, 1024x768? yeah, you're not far off that...), and there's simply not enough vertical space to display all the content without overlapping. There's no way for a Steam skin to dynamically adjust itself based on its content... So what do you propose I do?

**Comment by Hatomike** [comment]
I recall saying that there is an empty gap between "Last achievement" and the progression bar when you got all achievements from a game. (The "So close" one just disappear)
If you put "So close" after "Last achievement" in line, both problems should be resolved.

**Comment by DirtDiglett** [comment]
@Hatomike there are problems with having them side-by-side, the first being is that it can't have a variable width, it has to have a set width, so let's say for example I make it 500 pixels wide. That means that any achievements with wording that exceeds that get cut off, and it means that the total space used horizontally there would be 1048pixels used out of a 1366 pixel wide screen (500+500+24+24 spacing), meaning if he pulls up a broadcast the broadcast gets cut off. Ultimately, having such a small resolution leaves so little room to move it's silly.

**Comment by Hatomike** [comment]
@DirtDiglett 
Can't you just take the progress bar width, divide it by two and add spacing ?
Just replace overflowing text by "...". By looking at @iElCapitan screen, this could be good.

But I don't know if this can work with broadcast since I don't know how it look.

**Comment by DirtDiglett** [comment]
...Because that means any achievement that isn't at most two short single words like "Gift Grab" gets cut off. Using TF2 achievements here's some examples:

Not cut off:
- Gift Grab
- Lumberjack
- Get Along!

Cut off:
- Demoman Milestone 2
- Impenetrable Defense
- Friendship is Golden

When I did them side-by-side in Pressure I got a lot of complaints about the achievement text being cut off, so I resolved to avoid that in this version.

I can possibly just have the achievement area super long, I don't _want_ to do it, because it wouldn't be following the Material Design spec, but it's a potential solution.

**Comment by Hatomike** [comment]
I don't think this could bother me, but if peoples say so I can't do anything !
Hope you find something that can do the trick !

**Comment by leyyce** [comment]
@DirtDiglett 
Just wanted to report this "bug" to you. I personally can live with it and it's no big deal. 

"So what do you propose I do?"
I think the easiest way to solve this issue would be the idea suggested by @Hatomike but like I said if you don't want to change the layout of the skin for this little "bug " this is totally OK with me. Your skin so you decide :)

**Comment by Asphira** [comment]
I hate to suggest it but why not put achievements crap in the bottom right corner, instead of having it all list on the side, would work with smaller resolutions, and be able to keep it looking for the most part material design

**Comment by DirtDiglett** [comment]
I think what i'll end up doing is providing a replacement .layout file that will change the achievements to be side-by-side, but not make it the default, that way people with a decent screen res don't suffer the change but those with small resolutions can get this fixed too.

**Comment by DirtDiglett** [comment]
I've got a working tweak that will resolve this issue in the 1.0.1 release.

Closing.
