### ISSUE TITLE
Friend list: "Group"-Tab barely visible

### ISSUE THREAD

**Issue by leyyce** [DirtDiglett/Pressure2#22]
**Steam client beta?**
Yes.

**Does it happen without skin?**
No.

In the friend list the "Group"-Tab, or if "Group"-Tab is selected the "Friends"-Tab is barely visible.
I don't know why but on my screenshots you can see the buttons pretty well, however in reality I it's like the button is not there at all until I click on him (probably just to bright for me)

**"Group"-Tab almost invisible:**
![screenshot 11](https://cloud.githubusercontent.com/assets/13371024/13333202/1bc6e320-dc06-11e5-8a2c-c71ee58c5a9b.jpg)

**"Friends"-Tab almost invisible:**
![screenshot 13](https://cloud.githubusercontent.com/assets/13371024/13333201/1bc649c4-dc06-11e5-9b84-76497c755866.jpg)

**Comment by DirtDiglett** [comment]
Don't use the latest commits in the repo, use the stable release that I posted everywhere (https://github.com/DirtDiglett/Pressure2/releases/latest).
