### ISSUE TITLE
There is no maximize window button

### ISSUE THREAD

**Issue by big-mubble** [DirtDiglett/Pressure2#23]
There is no maximize window button next to the minimize and close window buttons. I opened the steam dev tool, and looked around in the layouts, and found something referring to a maximize button, also the minimize and close window ones. 
![pressure2screenshot dev](https://cloud.githubusercontent.com/assets/17509340/13371369/8d238bb0-dcea-11e5-8080-747ea322602c.PNG)
Is maximize window only not default, and can I enable it myself?
#### Does it also occur on Steam without the skin installed?

No, only Pressure2
#### Are you in the Steam BETA?

No
#### Are you using the latest release or a dev version

Latest Release
#### A screenshot of the issue.

![pressure2screenshot](https://cloud.githubusercontent.com/assets/17509340/13371342/eaa39c22-dce9-11e5-9c8e-43ae587a854b.PNG)
#### Steps to reproduce the issue.

No steps require

**Comment by DirtDiglett** [comment]
Ha! That's weird as hell. I didn't even realize it vanished, and can't see at a glance why it went on a walkabout. I'll get it sorted asap.

**Comment by big-mubble** [comment]
Cool, I wasn't sure if it was on purpose or not, so I'm glad I could help bring it to your attention.
