### ISSUE TITLE
Skin Animations Are Laggy

### ISSUE THREAD

**Issue by Sydch** [DirtDiglett/Pressure2#28]
**Description of the issue**
It seems laggy, when i tried to close Steam window it disappears very slowly.

**Does it also occur on Steam without the skin installed?**
Nope. Also i tried SteamAIR and Metro For Steam, none of them occurs this issue.

**Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?**
I was on Beta, then i opted out. It still occurs.

**What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)**
Windows 10 Pro 64-Bit

**Are you using the latest stable release or using the latest commit version?**
Tried both. Still occurs.

**A screenshot of the issue.**
Can't screenshot an animated thing, sorry :<

**Steps to reproduce the issue.**
Sign In, then it appears.

**Comment by DirtDiglett** [comment]
Duplicate of #27 and has been fixed for a 1.0.1 release. Closing.

**Comment by Sydch** [comment]
It's still occurs after bugfix update.

**Comment by avsaponchik** [comment]
Agreed

**Comment by Razzile** [comment]
a bit late I know but I still get major lag even on 1.0.1
