### ISSUE TITLE
Formatting anomaly "Steam - Self Updater"

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#30]
#### Description of the issue.

"A steam client update has been downloaded." is touching the top of the box which looks wrong in my opinion.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes & Yes.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10 Pro
#### Are you using the latest stable release or using the latest commit version?

Latest Commit version
#### A screenshot of the issue.

http://puu.sh/nrvTH.png
#### Steps to reproduce the issue.

Get a update for Steam.

**Comment by DirtDiglett** [comment]
Thanks for the report @crunzaty. Currently it appears to be impossible to adjust the Steam update dialog's positioning of elements in any way, no skin developer has been able to achieve this (Inhibitor, Asp and myself have tried to tackle this multiple times without success. So it may end up being unsolvable but I am going to try to take another look at it with fresh eyes and see if there's something we've all missed before.

**Comment by Asphira** [comment]
Should be fixable, seems to have a cached .res file, if we built the layout section for that (with guess work since we can not pull up the Check for updates window manually should be tweakable
"steam/cached/DialogCheckForUpdates_Expanded.res"

**Comment by Asphira** [comment]
Well layout changes did not fix it, some manual insetting and the like did though

**Comment by Asphira** [comment]
Just have to see if it effects next time it pops up
