### ISSUE TITLE
Wallet Amount gets in way of Store Drop Down

### ISSUE THREAD

**Issue by MrDowntempo** [DirtDiglett/Pressure2#31]
#### Description of the issue.

The Wallet amount beneath the Store Button interferes with the Store drop down menu
#### Does it also occur on Steam without the skin installed?

No
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

In Steam Beta.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10
#### Are you using the latest stable release or using the latest commit version?

Using version 1.0
#### A screenshot of the issue.

I tried, but couldn't screenshot my cursor :(
#### Steps to reproduce the issue.

When the wallet amount is displayed beneath the store button and you mouse over the store button, the drop down list is displayed. However as you drag your mouse down to select the items, and the mouse moves over the wallet amount, the drop down list disappears. It does reappear when the mouse hovers over the few pixels below the wallet amount, but if you move your mouse to fast, it can be missed entirely. This makes selecting items in that drop down more difficult than needed.

**Comment by DirtDiglett** [comment]
This has been resolved already under Issue #5 and is part of the 1.0.1 bugfix release I'll be doing shortly. Thanks for the report though :+1:
