### ISSUE TITLE
Tickbox gets obscured by Selected BG colour in tables

### ISSUE THREAD

**Issue by Asphira** [DirtDiglett/Pressure2#33]
#### Description of the issue.

Selected bg colour of text in tables covers selected tickbox entirely (unticked shows correctly)
#### Does it also occur on Steam without the skin installed?

Nope
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes in beta, In and out of beta I assume
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Win 8.1
#### Are you using the latest stable release or using the latest commit version?

Both development and stable
#### A screenshot of the issue.

[Example](https://www.dropbox.com/s/9pmkf8qs7ettt6x/Tickbox%20issue.png?dl=0)
#### Steps to reproduce the issue.

Use Pressure 2, select something in a table that has a tickbox

Potential fix, checked selected tickbox is set as render rather then render_bg? (have not looked into it just yet, just a guess)

**Comment by avsaponchik** [comment]
screenshot is 404, please drag it directly to git

**Comment by DirtDiglett** [comment]
Fixed in the development branch for a 1.0.1 release. Closing.
