### ISSUE TITLE
Download statistics text is black

### ISSUE THREAD

**Issue by supra107** [DirtDiglett/Pressure2#34]
#### Description of the issue.

The download statistics text is black, thus hardly readable.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes, and the issue doesn't occur when opted out.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 7 Ultimate x64
#### Are you using the latest stable release or using the latest commit version?

Latest commit.
#### A screenshot of the issue.

![steam_2016-03-04_19-40-20](https://cloud.githubusercontent.com/assets/15564069/13536583/11a25924-e241-11e5-915b-0857ecadb6ba.png)
#### Steps to reproduce the issue.

Open up the "Downloads" window.

**Comment by DirtDiglett** [comment]
I've fixed this up for a 1.0.1 release, forgot to note the issue in the commit so I'll manually close this now.
