### ISSUE TITLE
Steam uses >30% CPU when the friends list is open on the desktop.

### ISSUE THREAD

**Issue by DanzeFantaztic** [DirtDiglett/Pressure2#36]
#### Description of the issue.

When the friends list window is open on my desktop, the Steam client process uses above 30% CPU until I close the friends list window.
#### Does it also occur on Steam without the skin installed?

This only occurs when I have Pressure2 set as my skin.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

I am currently in the Steam Beta, but this still happens when I opt out of the beta.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10.
#### Are you using the latest stable release or using the latest commit version?

I'm using the latest stable release for Pressure2, v1.0.
#### A screenshot of the issue.

[With the default Steam skin.](http://i.imgur.com/zM6VI6k.png)
[With Pressure2 v1.0.](http://i.imgur.com/VWpVWl3.png)
#### Steps to reproduce the issue.

Just open the friends list and Steam instantly begins to use over 30% of your CPU.

**Comment by avsaponchik** [comment]
#27 #3 #28
