### ISSUE TITLE
Some overlay problems

### ISSUE THREAD

**Issue by SSadistic** [DirtDiglett/Pressure2#4]
1. "View friends is bugged" 
   ![2016-02-24_00001](https://cloud.githubusercontent.com/assets/4640551/13285135/a06ff77a-db01-11e5-8f8c-4a69f2dbc62a.jpg)
2. When you have less then 100FPS (1-99) - The FPS is shown as usual to the corner you've chosen, but when its 100 or more, the "PS" letters aren't shown at all, it's like - 100 F....
   ![2016-02-24_14-22-30](https://cloud.githubusercontent.com/assets/4640551/13285206/16261bf2-db02-11e5-8dc5-92e9448fb06f.png)

**Comment by Js41637** [comment]
FPS counter is indeed probably just a width issue however the Overlay, what resolution are you running at and are you in Windowed mode?

**Comment by SSadistic** [comment]
I was in windowed mode just for the FPS picture, but it's the same in full screen, however I'm always on full screen. 1360x768, but friends with 1920x1080 have the exact same problem. And yet this problem with the FPS doesn't exist on normal pressure for example. (Using it for a compare, since it's made by the same person)

**Comment by Js41637** [comment]
Hmm yeah i'm noticing some weird Overlay clips when playing some games at weird size and sometimes when in Windowed Mode.

**Comment by leyyce** [comment]
I've the same bug in the overlay if i play the game in 1366x768 res,
however if I play a game like CS:GO in 4:3 format with 1280x1024 res the overlay looks just fine:
![Image](http://i.imgur.com/YSP0uUA.jpg)

**Comment by DirtDiglett** [comment]
Hi @iElCapitan - thanks for letting me know about this one, it looks like I accidentally overlooked that some games and people use a lower widescreen resolution, and didn't account for this.

I will work on getting this fixed.
