### ISSUE TITLE
Traffic Lights for Mac?

### ISSUE THREAD

**Issue by sebj** [DirtDiglett/Pressure2#44]
#### Description

**_[Aesthetic Issue]**_

All Steam windows with this skin use Windows-style minimise, maximise and close buttons. Would it be possible to use OS X traffic lights on OS X (like those from the original Pressure skin)?

It's slightly weird and confusing to have to go to the right corner of the window (especially with a decent number of windows on screen), and doesn't fit in.
#### Operating System

OS X 10.11.3

**Comment by Asphira** [comment]
It would be possible, since you can define mac controls and place them separate to windows controls, would be up to Dirt to do though, think he went for the universal, it looks the same on each os due to material design aspects

**Comment by DirtDiglett** [comment]
VERY late reply sorry @sebj  but @Asphira is correct - Material Design guidelines are platform independant, they don't change the controls based on the host platform, so I chose to stick to that.
