### ISSUE TITLE
Download Page - Misaligned Text

### ISSUE THREAD

**Issue by Kobi-Blade** [DirtDiglett/Pressure2#45]
#### Description of the issue.

The text is misaligned on the Download Page.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10.
#### Are you using the latest stable release or using the latest commit version?

Latest stable release (1.0.1).
#### A screenshot of the issue.

http://imgur.com/fVKm9bj
#### Steps to reproduce the issue.

Download a game, check progress on download page.

**Comment by Asphira** [comment]
That is due to you not having DirectWrite on (can turn it on in Settings/Interface) which is recommended for this theme for the additional font smoothing, if you do however have DirectWrite on then let us know

**Comment by Kobi-Blade** [comment]
It's on by default.

**Comment by Asphira** [comment]
Odd because I only had that misaligned text issue with it off, but showed correctly on,

**Comment by Asphira** [comment]
What occurs if you turn it off, apply and then click it back on?

**Comment by Kobi-Blade** [comment]
Doesn't change a thing, It works fine on default skin.

**Comment by Asphira** [comment]
Really bizarre since I am not replicating it by turning it off, on, changing to megabits/megabytes, its showing correctly, Might redownload the skin and save seperate, maybe i have a fix in mine that i forgot about

**Comment by Asphira** [comment]
Hmm 1.01 still does not seem to have the issue for me :/ sorry iKobi

**Comment by Kobi-Blade** [comment]
Installed "Roboto Medium" fonts that where missing from my system, now it makes a difference.

The issue with DirectWrite is less pronounced and noticeable, but it's still there, the text is still not aligned.

If we compare it to the default skin, the text is perfectly aligned regardless of the setting.

![Default Skin](https://cloud.githubusercontent.com/assets/15495525/13704440/e6e22d2e-e793-11e5-820d-890981777df2.jpg)
![Pressure² Skin](https://cloud.githubusercontent.com/assets/15495525/13704441/e70585c6-e793-11e5-9052-7a0cb265a6a4.jpg)

**Comment by Asphira** [comment]
The reason default aligns regardless is because of its relatively generic font that direct write does not alter the size of it much when bolding since the font itself is barely bold as it is

What is even more odd is even using pressure 2 1.01 I am not having the misaligned issue with direct write on (with it off, the font is evidently smaller and misaligned)
![odd](https://cloud.githubusercontent.com/assets/8689925/13721118/a1ea5dea-e856-11e5-9c8f-8a77de5b8ce3.png)
