### ISSUE TITLE
Bug in broadcasting settings window

### ISSUE THREAD

**Issue by WildManiac** [DirtDiglett/Pressure2#46]
#### Description of the issue.

When in the Broadcasting Settings Window (And "Anyone can watch my games" is selected) there is an orphaned checkbox floating at the top.
#### Does it also occur on Steam without the skin installed?

No
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Beta: Yes.
Stable: Not tested.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 7
#### Are you using the latest stable release or using the latest commit version?

Latest stable release (1.0.1)
#### A screenshot of the issue.

![broadcast error](https://cloud.githubusercontent.com/assets/11233971/13588858/3109f7b0-e4a1-11e5-8f77-85596387d001.jpg)
#### Steps to reproduce the issue.
1. Go to Broadcasting submenu in settings window
2. If not already selected, change privacy setting to Anyone Can Watch My Games
#### Additional Note

I went and tried to find the offending/missing code. It seems that there should be
`ShowReminder`
at the end of
`control=IncludeDesktop,RecordSystemAudio,RecordMic,ShowDebugInfo`
in settingssubbroadcast.layout.

**Comment by Asphira** [comment]
Yep if ShowReminder is added after that it shows correctly

eg
control=IncludeDesktop,RecordSystemAudio,RecordMic,ShowDebugInfo,ShowReminder

**Comment by Js41637** [comment]
Is this still an issue? I can't reproduce it.
