### ISSUE TITLE
No "Offline" (etc.) options in chat window 

### ISSUE THREAD

**Issue by leyyce** [DirtDiglett/Pressure2#47]
#### Description of the issue.

Missing the option to go offline (etc.) in Steam chat

![screenshot 18](https://cloud.githubusercontent.com/assets/13371024/13646969/3263cba8-e632-11e5-8583-cc583fd06a30.jpg)
![screenshot 17](https://cloud.githubusercontent.com/assets/13371024/13646973/362280d6-e632-11e5-8557-4dc0e2e53b78.jpg)
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes and yes
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10
#### Are you using the latest stable release or using the latest commit version?

Latest commit
#### A screenshot of the issue.

See above
#### Steps to reproduce the issue.

/

**Comment by DirtDiglett** [comment]
Right click your name.
