### ISSUE TITLE
Wallet Amount Overflows to Adjacent Tab

### ISSUE THREAD

**Issue by fadillzzz** [DirtDiglett/Pressure2#5]
Nothing too major, but kinda ruins the look a little bit.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA?

Yes.
#### A screenshot of the issue.

![](http://i.imgur.com/4fTmAH5.png)
#### Steps to reproduce the issue.

Launch Steam and log in to an account associated with a low-value currency.

**Comment by Js41637** [comment]
Yes this is an issue, it is actually even worse if you get a Steam Refund as Steam adds a massive '$xxxx Pending` to the end. I'm not sure what will be done about this.

**Comment by fadillzzz** [comment]
I'm not very familiar with how Steam skins work under the hood, but is it not possible to make the spacing dynamic in any way?

**Comment by Js41637** [comment]
We wish, dynamic spacings/positions in Steam is all but non-existent.

**Comment by TripleSquare** [comment]
Happens too with CHF (Swiss frank) 
![pressure2_chfissue](https://cloud.githubusercontent.com/assets/4160612/13285993/b48a3ab6-dafe-11e5-97b5-927d37b801b2.png)

maybe you guys could add this next to the username? 
![image](https://cloud.githubusercontent.com/assets/4160612/13286023/e2372050-dafe-11e5-9fba-8b2787d1e4d7.png)

**Comment by Js41637** [comment]
It will happen with pretty much any current that doesn't have a 1 letter currency symbol and uses more than 4 numbers, $12.34 will look fine but anything else will not look right unfortunately. I'm not sure if Dirt took this into account when implementing it. If it is to be fixed, it will have to be moved.

**Comment by DirtDiglett** [comment]
Oh wow. That was a horrible oversight on my part, i'm a bit dissapointed that I didn't consider other currencies for this, but even then I was not aware that any currency went to 5+ digits on Steam, Rp 53,482.25 is something I would never have accounted for without it first being brought to my attention so thankyou for that.

I will work on getting this sorted, I'm not yet sure how I will approach it, but when I have a potential solution would you be ok to test it for me before I release it?

**Comment by fadillzzz** [comment]
@DirtDiglett Sure, I don't mind.

**Comment by DirtDiglett** [comment]
Ok, I'd like to try out a fix that should work for every currency, can you please download the attached file and put steamrootdialog.layout in /Pressure2/resource/layout/ and replace the existing one, then restart Steam and send me a screenshot of what it looks like. Hopefully it works as I intend it to.it works as I intend it to.

[Wallet Balance Fix.zip](https://github.com/DirtDiglett/Pressure2/files/149225/Wallet.Balance.Fix.zip)

**Comment by fadillzzz** [comment]
This is what I got after installing the fix:

![](http://i.imgur.com/2Llbp3X.png)

**Comment by DirtDiglett** [comment]
Fantastic! Works as I had hoped, it should automatically center the funds value at all times for all currencies, with the added bonus that it doesn't cause the dropdown list to bug out like it did prior.
