### ISSUE TITLE
Can't use the login panel

### ISSUE THREAD

**Issue by Bearnaut** [DirtDiglett/Pressure2#53]
#### Description of the issue.

the login panel doesn't load the way it should preventing me from logging in
#### Does it also occur on Steam without the skin installed?

Nope
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

It happens on both
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 7
#### Are you using the latest stable release or using the latest commit version?

Yes
#### A screenshot of the issue.

http://i.imgur.com/k0c6BgW.jpg
#### Steps to reproduce the issue.

upon installing the skin after following the instructions, the login screen appears like shown on the screenshot and it does not allow any info to go in

**Comment by Js41637** [comment]
Honestly i've got no idea why this could happen. Have you installed the fonts required for the skin?
