### ISSUE TITLE
confusing collapse/expand icons in lists

### ISSUE THREAD

**Issue by realjck** [DirtDiglett/Pressure2#55]
I really like this UI, but I think that there is a mistake with collapse/expand icons.

The confusing comes that the icon shows a 'state' and not an 'action', here a small fix I made, using + and - icons instead of arrows that are in the wrong directions in my opinion.

What do you think about it? I can PR if you think it makes sense :
![03-07-2016 20-59-45](https://cloud.githubusercontent.com/assets/5341656/16547093/e2988268-4161-11e6-9010-0e5984589052.jpg)

**Comment by DirtDiglett** [comment]
The list controls are as dictated by the Material Design guidelines. See https://material.google.com/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by realjck** [comment]
The list control is invalid according to the guidelines because it doesn't follow the first main rule: motion.

**Comment by Js41637** [comment]
You can't animate in the Steam Client tho lol

**Comment by DirtDiglett** [comment]
As Js said, there's no control in a steam skin that lets the theme alter animations.

**Comment by realjck** [comment]
And as I said there's no Material Design element that doesn't use motion.

Motion is the # 1 guideline of Material Design, using this graphic element without motion makes it invalid and confusing. But this is not a problem because I updated the skin on the version I use, so it's ok for me.

**Comment by Js41637** [comment]
I guess if we can't use motion we might as well trash the whole skin.

**Comment by realjck** [comment]
Google Material Design is not a trend, it's a whole set of guidelines that have to be respected alltogether to be compliant. Making a skin 'inspired' by Material Design that not fully respect the rules is a huge mistake in my opinion.
And by the way, what about the colors? Material Design has a very specific color tones guildeline that is not present in this skin, and that could be.

The skin can not pretend to follow the Material Design if it can't be and will never be.

Concerning my initial post I will just terminate by posting this GIF, so contributors will make their own opinion. And yes, these icons are the 'old way' to do, but they work far better that up/down arrows with no motion.

![collapse-expand-icons](https://cloud.githubusercontent.com/assets/5341656/21140999/1c9ca5ee-c13b-11e6-8e2d-20f1da8e7f15.gif)

**Comment by DirtDiglett** [comment]
> Google Material Design is not a trend, it's a whole set of guidelines that have to be respected alltogether to be compliant. Making a skin 'inspired' by Material Design that not fully respect the rules is a huge mistake in my opinion.

Well then clearly Pressure2 was a mistake. There's only so much the Steam theme engine can do, and it's so incredibly limited, but I abided by every little thing I possibly could to get as close as possible. But fuck, if you can't do it 100% might as well not do it right?

> And by the way, what about the colors? Material Design has a very specific color tones guildeline that is not present in this skin, and that could be.

Mind giving some examples? barring the small flourishes (Using a different, but close, grey for the primary header that suits Steam's branding before their whole weird blue shift) it uses the Material Design palette. In fact, open up colors.styles and you'll see I have the palette in there exactly and use it accurately throughout.

Material Design guidelines for color have no qualm with using colors outside the palette, but I did so sparingly.

> The skin can not pretend to follow the Material Design if it can't be and will never be.

Why not? I wanted a Material Design Steam, and did the absolute best I could with what was available. Short of Valve doing it themselves it's the best it can possibly be.

> And yes, these icons are the 'old way' to do, but they work far better that up/down arrows with no motion.

Nah, Microsoft went away from the +/- for expand/collapse in their products, as did Apple, as did Google, as does Ubuntu and most nix distros I just had a looksie at... In fact, they all seem to use... shock horror - arrows. Looks like there's an industry trend so either they are all horribly wrong, or you are in your opinion.
