### ISSUE TITLE
German language issues(modified version DarkPressure²).

### ISSUE THREAD

**Issue by Legion495** [DirtDiglett/Pressure2#60]
#### Description of the issue.

German Text's go way out of the Settings menu.
And some text gets cutoff.
#### Does it also occur on Steam without the skin installed?

No it doesn't.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Opted out.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Win10 latest Version(July-August Update)
#### Are you using the latest stable release or using the latest commit version?

I use the modified DarkVersion which should only differ by color. 
I testet this version of yours
http://www.pressureforsteam.com/ (7.3.2016)
#### A screenshot of the issue.

![press](https://cloud.githubusercontent.com/assets/15214766/17532148/87ac2cca-5e7f-11e6-96d8-d0757ac8c20f.PNG)
![press2](https://cloud.githubusercontent.com/assets/15214766/17532176/a1553068-5e7f-11e6-8b63-643aa8e7adce.PNG)
![press3](https://cloud.githubusercontent.com/assets/15214766/17532187/b25a20e4-5e7f-11e6-8252-ed52cfa6ee7f.PNG)
#### Steps to reproduce the issue.

Set your language to german own the latest Windows10 Upgrade which screws up Fonts and everytime anything states a restart is needed thats out of the window.
This is only the Settingswindow if possible a small gain about half a cm in width and height would fix this.

I do not expect changes because that's language related but I thought people would like to know.

**Comment by Js41637** [comment]
Seeing as your using the dark version, there isn't much I can do but I believe the bug has been fixed in the development version.
