### ISSUE TITLE
Better dropdown lists

### ISSUE THREAD

**Issue by boswelja** [DirtDiglett/Pressure2#64]
Right now I feel the dropdown lists aren't very good, and could be improved by using either material dropdown styling rules, or the latest windows 10 dropdown styles

**Comment by boswelja** [comment]
Not sure how to tag this as an enhancement :(

**Comment by Js41637** [comment]
We don't have any control over the dropdowns and by dropdowns I assume you mean ones like
![image](https://cloud.githubusercontent.com/assets/6258213/19024657/a1594d0c-8953-11e6-8763-7112bb4c5b43.png) we can only really change the color.

**Comment by boswelja** [comment]
:(
