### ISSUE TITLE
Weird text scaling in settings

### ISSUE THREAD

**Issue by NF-Codestuffs** [DirtDiglett/Pressure2#66]
#### Description of the issue.

The text scales and shift weirdly in the settings
#### Does it also occur on Steam without the skin installed?

No
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10 anniversary
#### Are you using the latest stable release or using the latest commit version?

latest stable
#### A screenshot of the issue.

http://imgur.com/a/0f0c3
#### Steps to reproduce the issue.

open settings and go to the tabs

**Comment by Js41637** [comment]
That's just because the skin is out of date. You can use the dev version in the development branch.

https://github.com/DirtDiglett/Pressure2/tree/development and download it as a zip.

**Comment by NF-Codestuffs** [comment]
I don't go there often, so I'll just update when the next stable comes out
