### ISSUE TITLE
A older version

### ISSUE THREAD

**Issue by g4msGaM3R** [DirtDiglett/Pressure2#68]
i have a question for you !
how can i get a older version of  pressure like 1.0.0?
please tell me if i can .
i put a picture with the older version what i like.
![pressure for steam older version](https://cloud.githubusercontent.com/assets/23259696/20005095/67933a14-a290-11e6-9749-b603299346e2.png)

Thank You !

**Comment by leyyce** [comment]
If you're asking if you still can download the original Pressure(1) skin (the one in the screenshot) the answer is [yes](https://github.com/DirtDiglett/Pressure-for-Steam/releases/tag/1.0.6). Hope that will help you ;)

**Comment by FlamingFox911** [comment]
I'd also recommend using the Pull Request version [here](https://github.com/FlamingFox911/Pressure-for-Steam/tree/Steam-Client-Beta) as it is more up to date.
