### ISSUE TITLE
Didn't think the dark version would be this dark. Interface is broken.

### ISSUE THREAD

**Issue by cowcalf** [DirtDiglett/Pressure2#72]
#### Description of the issue.
Installed the dark version of Pressure^2 Interface is completely blacked out. 

#### Does it also occur on Steam without the skin installed?
No.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10 on Surface Pro 4

#### Are you using the latest stable release or using the latest commit version?
Yes.

#### A screenshot of the issue.
https://puu.sh/tzv9t.png

#### Steps to reproduce the issue.
None.

**Comment by DirtDiglett** [comment]
You wanted a DARK MODE, you got a dark mode 😝 

Jokes aside, have you done a complete clear of your skin folder and reinstalled it from a fresh download? This usually happens with a corrupted download/Missing files.

**Comment by sli** [comment]
The fix does not work. All the files are in the archive, but every file is empty. The same is not true of the standard release, only the dark version.

**Comment by Js41637** [comment]
Files are definitely not empty for me. I open it fine with 7zip

**Comment by avsaponchik** [comment]
@sli sometimes when you download from github you can get empty subfolders. no idea why that happens.
