### ISSUE TITLE
UI fonts are not consistent on Linux

### ISSUE THREAD

**Issue by orffen** [DirtDiglett/Pressure2#73]
#### Description of the issue.
Various UI elements are using sans-serif font instead of the Roboto font.

If I change fontconfig settings to set a different font as "sans-serif" those elements change to the new font when relaunching Steam.

#### Does it also occur on Steam without the skin installed?
N/A

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Not in BETA

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Linux Mint 18.1

#### Are you using the latest stable release or using the latest commit version?
Stable

#### A screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/2225985/22312193/f73b0fc4-e3aa-11e6-96f1-bfe95cb72360.png)

#### Steps to reproduce the issue.
Launch Steam

**Comment by orffen** [comment]
Another shot - note the top menu and the font inconsistency on the download speed elements.
![image](https://cloud.githubusercontent.com/assets/2225985/22312281/523a5dc6-e3ab-11e6-895e-6d4e0cd7c523.png)

**Comment by vdrandom** [comment]
Fonts in Steam on Linux are rendered slightly larger than on Windows. Pressure suffers from it far less than some of the other skins (notably Air).

**Comment by Alkaris** [comment]
I fixed inconsistent font issues just by resizing the fonts to new appropriate sizes which look nicer. I did some customizing to resize some buttons to match as well

this is my quick-fix solution to change font-size on Linux for Pressure⁲ DARK 1.0 skin
```
find . -type f -exec sed -i 's/font-size=15/font-size=12/g' {} \;
find . -type f -exec sed -i 's/font-size=14/font-size=12/g' {} \;
find . -type f -exec sed -i 's/font-size=18/font-size=14/g' {} \;
find . -type f -exec sed -i 's/font-size=19/font-size=14/g' {} \;
find . -type f -exec sed -i 's/font-size=30/font-size=18/g' {} \;
find . -type f -exec sed -i 's/font-size=16/font-size=12/g' {} \;
find . -type f -exec sed -i 's/font-size=26/font-size=16/g' {} \;
find . -type f -exec sed -i 's/font-size=48/font-size=20/g' {} \;
find . -type f -exec sed -i 's/font-size=17/font-size=14/g' {} \;
find . -type f -exec sed -i 's/font-size=20/font-size=14/g' {} \;
find . -type f -exec sed -i 's/font-size=21/font-size=14/g' {} \;
find . -type f -exec sed -i 's/font-size=31/font-size=20/g' {} \;
find . -type f -exec sed -i 's/font-size=28/font-size=16/g' {} \;
find . -type f -exec sed -i 's/font-size=29/font-size=16/g' {} \;
find . -type f -exec sed -i 's/font-size=60/font-size=20/g' {} \;
find . -type f -exec sed -i 's/font-size=61/font-size=20/g' {} \;
find . -type f -exec sed -i 's/font-size=25/font-size=16/g' {} \;
```
You can change the font sizes to anything you want, those are just my preference that suits better.
just follow this example below to know what you're changing.
```
sed -i 's/<default_font_size>/<new_font_size>/g' {};
```

find the default font-size values by doing grep command.
```
grep --include=\*.{styles,layout} -rnw './Pressure2-DARK-1.0' -e "font-size"
```

**Comment by DirtDiglett** [comment]
@vdrandom is spot on - It's the different in font renderer that causes it. 

@Alkaris Good to see you've found a solution. If you're able to upload me a .zip of your resulting theme with the fonts the correct size for Linux I can implement it in a future release, as I can set the font-size specific to Linux.

**Comment by DirtDiglett** [comment]
I've been running ubuntu via VirtualBox to test, and managed to build a list of corresponding font sizings between Windows, MacOS, and *nix, so the commits I've done for a 1.1 release should make it much more akin to how I intended it to look :)
