### ISSUE TITLE
HiDPI Support?

### ISSUE THREAD

**Issue by drohm** [DirtDiglett/Pressure2#74]
On hidpi systems, the interface is extremely small.  Will there possibly be support for hidpi displays?

Resolution: 3840x2160 (16x9)

I'm not using the Beta steam client.

OS: LinuxMint 18.1 Cinnamon 64-bit

Version tested: Pressure2-1.0.3 and Pressure2-Dark-1.0

![pressure2-hidpi](https://cloud.githubusercontent.com/assets/184959/22409894/f3b379ca-e65e-11e6-9774-68432c7a8882.png)

**Comment by DirtDiglett** [comment]
I originally had planned it, but it's a lot of effort as I'd have to make a whole new version of the skin specifically for larger displays, and then do I do it for 4K only? 5K? Retina? It's an exorbitant amount of work that I am unwilling to commit to.

On the positive side, it looks like SteamU is coming soon(tm), and if it uses PanoramaUI as I suspect I can make a theme for it that is fully responsive.
