### ISSUE TITLE
Decompression Failed on Mac

### ISSUE THREAD

**Issue by shaq19** [DirtDiglett/Pressure2#75]
#### Description of the issue.
When downloading pressure2 decompression always fails on mac. At first the message says the download is incomplete, then when clicking the file it says failed to decompress. this happens on chrome and safari for mac

#### Does it also occur on Steam without the skin installed?
It doesn't reach that stage. the zip file downloads however cant be decompressed

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Not in steam Beta

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Mac OSX 10.12.3 (newer version)

#### Are you using the latest stable release or using the latest commit version?
latest stable release

#### A screenshot of the issue.
![screen shot 2017-01-30 at 11 29 05](https://cloud.githubusercontent.com/assets/25431176/22421520/7e4995d0-e6df-11e6-9722-f5d44807401d.png)

#### Steps to reproduce the issue.
just try downloading pressure2 on mac

**Comment by DirtDiglett** [comment]
Tried using any other utilities like 7Zip? I've done nothing magical to the files, so I'm unsure why it wouldn't be working for you.

**Comment by agsimmons** [comment]
I'm having the same issue on my MacBook Pro, macOS 10.12.2

The Unarchiver unzips the file correctly. unzip from the command line says the file is valid, and 7Zip on Windows also says the file is valid

**Comment by shaq19** [comment]
Thanks mat and Andrew. haven't tried 7zip may try that to see if it helps
but it seems my Mac is rejecting to fully download the file in the first
place. If I view the download process it always fails the download right
when it's about to finish. Then adds the decompression message.  I guess
it's possible the new Os versions could be creating the problem.

**Comment by agsimmons** [comment]
I tried downloading it on Linux and the file has the same MD5 hash as the file when downloaded on macOS, so it doesn't appear to be a problem with the file not being completely downloaded

**Comment by shaq19** [comment]
Ohh okay is there anything you recommend i do on my end? Or just sit tight

**Comment by FlamingFox911** [comment]
Is this only happening with Unix and Mac OS? Have you tried a different OS and downloaded that? Just thinking out loud here. Also, crazy thought: Have you tried turning off your firewall or enabling GitHub IP address?

**Comment by shaq19** [comment]
No I haven't, my MacBook is the only system available to me.

**Comment by agsimmons** [comment]
I downloaded it on windows as well. All three downloaded files show the same MD5 hash, so it is not an issue with downloading the file

Edit: The has for Pressure2-1.0.3.zip is 545BCFC5501BFED73F9FE0CA6C38F05D if you want to verify it.

What program do you use to create the ZIP files for Pressure2?

**Comment by FlamingFox911** [comment]
I just downloaded the zip file on my end, same checksum value as you said.

![untitled](https://cloud.githubusercontent.com/assets/11638944/23335294/83dc291c-fb80-11e6-8d7c-1199eb2c9335.png)

Works perfectly fine on my end. This might be more of a problem with your connections to the GitHub domain rather than the actual file itself. Check your networking to see it GitHub is allowed full access.

As for making the zips, I know that you can rig GitHub to generate a release for you, but I am unsure if that's what DirtDiglett is doing. I am using WinRAR if that's any help to you.

EDIT: After some quick sniffing, I found this: [https://discussions.apple.com/thread/2336773?tstart=0](https://discussions.apple.com/thread/2336773?tstart=0). Perhaps it can help?

**Comment by shaq19** [comment]
So I just found out downloading the file straight from github works fine
and I was able to download pressure 2. However @ www.pressureforsteam.com
I can't download any of the versions. Its the dark version I would like to
use but I can't find it on github.

**Comment by FlamingFox911** [comment]
Sorry for late reply. To get darkmode, go to the Pressure2 github, hit the branches tab and select Dark-Mode... or click this https://github.com/DirtDiglett/Pressure2/tree/Dark-Mode :P

**Comment by shaq19** [comment]
Thanks a lot for the help guys, got it working perfectly!
