### ISSUE TITLE
Fix for Account Balance

### ISSUE THREAD

**Issue by Alkaris** [DirtDiglett/Pressure2#77]
Taken from this users person post [here](http://steamcommunity.com/groups/pressureskin/discussions/0/133255957991925251/) on the Steam Group for Pressure for the Pressure⁲ DARK 1.0 skin. The awkward placement of the Account Balance above the name as shown here

![](https://i.imgur.com/9GEvZ1M.png)

and so I made my own fix to that to put it in a more appropriate place that looks consistent with the rest of the layout design like so

![](https://i.imgur.com/3tUac43.png)

My solution was by changing it to this

```
region {
			name=accountbalance
			y=20
			x=865
			width=205
			height=15
		}

		place {
			control=account_balance
			region=accountbalance
			align=top-right
			y=2
		}
```

open up `steamrootdialogue.layout` in `/Pressure2-DARK-1.0/resource/layout` and search for that line and save changes.

**Comment by DirtDiglett** [comment]
This isn't something to "Fix", I put it where it is for a reason.

**Comment by Alkaris** [comment]
It looks like a stupid placement to me, and I'm sure others may agree too. Doesn't look consistent with the rest of the layout.

**Comment by Js41637** [comment]
¯\_(ツ)_/¯

**Comment by DirtDiglett** [comment]
It may look stupid to you, but the great thing about being the creator of the skin is that I can say - "I don't give a shit."

You're free to use your own changes to it, and can share them, but I don't need to include it in the main repo
