### ISSUE TITLE
High CPU load and low performance when playing animation or scrolling

### ISSUE THREAD

**Issue by noddinagushpa** [DirtDiglett/Pressure2#78]
#### Description of the issue.
High CPU load and low performance when playing animation or scrolling

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Win10 after1611

#### Are you using the latest stable release or using the latest commit version?
Yes.

#### A screenshot of the issue.
![default](https://cloud.githubusercontent.com/assets/25709695/22855966/880cbc76-f0c3-11e6-8c05-c3a2160d5f2a.JPG)

#### Steps to reproduce the issue.
open friendlist/moving cursor among friends' names/scrolling
The animation is very laggy, only3~5 fps I think.
It seems this problem had been issued , But still got the problem on 1.0.3 :(
(I was scrolling/Steam CPU rise to about 30% immediately from about 1%/This kind of lag also happens during any other animation)
(Just a guess, if you don't get lag like this without anniversary windows10, then it could be related to some changes in 1611 about directx api?)

**Comment by noddinagushpa** [comment]
Update: It is extremely laggy when I login "Friends", and somehow get better performance when is set to "off line" (not offline mode)

**Comment by ChibiChoko** [comment]
I have this issue as well, however I *am* on the Steam Beta and I'm using the Dark version.

**Comment by noddinagushpa** [comment]
Oh seems I made it wrong, high cpu load was not particularly related with this single skin, it seems to happen in all skins including default skin...
The low performance problem exist only on the two pressure2 skins(light/dark), while pressure1 not.

**Comment by ChibiChoko** [comment]
Yeah I tested it with other skins and had the same results.
