### ISSUE TITLE
Friends and Settings tabs

### ISSUE THREAD

**Issue by GitHubUserNumber2** [DirtDiglett/Pressure2#8]
Friends and settings tab got that "laggy" animations. At least for me.

Not beta.
http://i.imgur.com/nFZQEQl.gifv
Just open up friends or settings tabs.

**Comment by katanacrimson** [comment]
Could use ShareX to do a screen record, then upload that somewhere.

**Comment by GitHubUserNumber2** [comment]
Done and done.
Thanks.

**Comment by DirtDiglett** [comment]
I believe this may be a sympton of Issue #3 but can you confirm for me if you are also experiencing the high CPU usage when using the skin? If so, i'll merge this issue report with #3, if not I'll keep it seperated.

**Comment by DirtDiglett** [comment]
@GitHubUserNumber2 it's been 3 days, can you please let me know what the deal is here... Otherwise i'll close the issue as invalid.

**Comment by Asphira** [comment]
The only thing I could seem to see that is the issue, is that the chat tab insets itself just after loading initially, most times the window loads so fast that its not even noticeable, but due to custom insetting, pretty certain this is not fixable (If that is the issue)
