### ISSUE TITLE
Pressure2-Dark - Categories in Small Mode are White

### ISSUE THREAD

**Issue by serioustable** [DirtDiglett/Pressure2#80]
#### Description of the issue.
When Steam is set to small mode, the categories in the Games list are colored white.

#### Does it also occur on Steam without the skin installed?
No, but the categories aren't regularly colored.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I am not in the Beta

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Latest Stable Release

#### A screenshot of the issue.
![pressure2darkcatbug](https://cloud.githubusercontent.com/assets/17442995/23096371/afa380c2-f5e0-11e6-867a-db5220a77756.PNG)

#### Steps to reproduce the issue.
* Install Pressure2-DARK-1.0.0
* Install Fonts
* Change Skin
* Set Steam to Small Mode
* Set something to a category.

**Comment by Dave247** [comment]
Fixed in b07e18b44aa8d7595240adafa2a2c0c535ae0beb, though now there is still a small white line I don't know how to get rid of, but it's at least a lot better then before.

**Comment by Dave247** [comment]
This issue was moved to Dave247/Pressure2#7
