### ISSUE TITLE
Steam deletes Contents/MacOS/skins directory every time it loads

### ISSUE THREAD

**Issue by kriskropd** [DirtDiglett/Pressure2#81]
#### Description of the issue.
Steam deletes Contents/MacOS/skins directory every time it loads

#### Does it also occur on Steam without the skin installed?
Yes

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Mac OS X 10.10.5

#### Are you using the latest stable release or using the latest commit version?
Latest Stable Release

#### Steps to reproduce the issue.
```
cd /Applications/Steam.app/Contents/MacOS/skins/
mkdir Pressure2
cd Pressure2
curl -JOL "https://github.com/DirtDiglett/Pressure2/releases/download/1.0.3/Pressure2-1.0.3.zip"
unzip Pressure2-1.0.3.zip
```
Then in Steam, go to preferences and realize the dropdown list for interface skins is not populating like it does on Windows. So I restarted Steam to update the dropdown, but then I noticed Steam was outright deleting the skins directory I created.

Tried to also create the skins directory at ~/Library/Application Support/Steam/skins but Steam also ignored this directory (though did not delete it on start.

**Comment by DirtDiglett** [comment]
> **Does it also occur on Steam without the skin installed?**
> 
> Yes

Then it's not a Pressure2 Issue, you'll have to report it directly to Steam/Valve

**Comment by czamp** [comment]
@kriskropd If you haven't figured this out by now, the correct location to install the skin on Mac OS 10.12 and 10.13 (possibly earlier versions, but I can't test it at the moment) is `~/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/skins`
