### ISSUE TITLE
Major lag problems.

### ISSUE THREAD

**Issue by lavendertheghost** [DirtDiglett/Pressure2#84]
#### Are you using Pressure2 or Pressure2 Dark?
Normal

#### Description of the issue.
The issue generally revolves around that pressure2 uses over twice as much power than any other skin. This is probably due to animations constantly occuring.

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Yes, and its not related. Steam BETA is lacking at this time.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 7

#### Are you using the latest stable release or using the latest commit version?
Stable

#### A screenshot of the issue.
None

#### Steps to reproduce the issue.
Use pressure2 on steam

**Comment by MartorSkull** [comment]
this is a killer for me, the only reason i don't use this skin is because of the lag

**Comment by DirtDiglett** [comment]
I've had reports from people randomly being affected by performance issues with the skin. Never found the root cause, never found the common thread linking those afflicted. Tried to solve the problem, but ultimately never found a solution and I've given up. Sorry.
