### ISSUE TITLE
Change online-status appears clickable, but isn't

### ISSUE THREAD

**Issue by wandt0n** [DirtDiglett/Pressure2#85]
#### Are you using Pressure2 or Pressure2 Dark?
I'm using the Dark one, but tried in both versions. Dowloaded fresh today.

#### Description of the issue.
In friends tab is a small arrow besiedes your username in the original skin. Click him and a dropdown appears, where you can set your online status. Not only me use this frequently. It's necessary if you don't open it to play and close when stop to play. In Pressure2 skin appears the name at the bottom of the friend-section und under it your actual status (f.e. "online"). If you hover with your mouse on this, it makes the colour of "[Username] paragraph [online-status]" a bit lighter, but however it is not clickable. I hope you just forgot to implement it, otherwise I'll have to use the standart theme :/

#### Does it also occur on Steam without the skin installed?
No.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Win 10

#### Are you using the latest stable release or using the latest commit version?
v1.0.4 (Dark v1.0)

#### A screenshot of the issue.
![screenshot 29](https://cloud.githubusercontent.com/assets/27301962/24925283/07e236a8-1ef8-11e7-922e-2b4f03e77801.png)

#### Steps to reproduce the issue.
None. Install theme.

**Comment by Dave247** [comment]
You can activate it by right and not left clicking.

**Comment by wandt0n** [comment]
Feels so stupid right now, thought I tried that either xD
I'm so sorry. Great work.
