### ISSUE TITLE
High resolution issue

### ISSUE THREAD

**Issue by NYPD** [DirtDiglett/Pressure2#86]
Using the latest version of Pressure 2 Dark, on high res setups (2560 x 1440), the light blue background ends sharply.

This is on Windows 10.0.15063 Build 15063

https://i.imgur.com/sEy33vo.png

**Comment by icarusmiles** [comment]
Yeah, reproducible. Same issue with 4k

**Comment by Dave247** [comment]
It also seems to affect the light version as well, and will happen if the window is stretched beyond a certain point on any resolutions.

**Comment by Dave247** [comment]
This issue was moved to Dave247/Pressure2#9

**Comment by Dave247** [comment]
I've stretched the image making it wider so it doesn't cut off on larger resolutions. Until it gets added to the main repo you can download it from my fork.

**Comment by DirtDiglett** [comment]
Thanks for resizing the existing image in my absence @Dave247 - that solves the problem quick and dirty but I've recreated the image from the start to avoid the artifacting and poor quality a simple resize creates.

It'll be included with a 1.1 release.
