### ISSUE TITLE
Lag and FPS drops using Overlay....

### ISSUE THREAD

**Issue by luizmp** [DirtDiglett/Pressure2#88]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
Hello there, I just loved the skin... using Dark Version... but I think I'll have to revert it to another skin until it's more improved. Running a game and using Steam Overlay is a FPS killer! With no open windows, 100 FPS.... open Friends... 50 FPS... open Player... 20 FPS... so it's too laggy... too problematic right now.. I really wish you could fix that and I'll come back here to say i'ts ok and that I'm using it again! But Thanks for the nice skin man!! Really enjoyed!

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10 x64

#### Are you using the latest stable release or using the latest commit version?
Darken Version 1.0.0

**Comment by DirtDiglett** [comment]
I've had reports from people randomly being affected by performance issues with the skin. Never found the root cause, never found the common thread linking those afflicted. Tried to solve the problem, but ultimately never found a solution and I've given up. Sorry.
