### ISSUE TITLE
Chat text selection bugged.

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#92]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
While selecting the chat text, the selection isn't highlighted for the friend's message, while it is highlighted for my messages as well as the name.

#### Does it also occur on Steam without the skin installed?
No.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10
#### Are you using the latest stable release or using the latest commit version?
Yes.

#### A screenshot of the issue.
https://gyazo.com/0c53cde80ca0f84b56898bc2e6d573c4

#### Steps to reproduce the issue.
Just try selecting in an active chat.

**Comment by parkour86** [comment]
I'm having this same issue. If I close the chat and reopen it I can highlight my friends messages. I'm using Ubuntu 16.04

**Comment by avsaponchik** [comment]
What CTRL+A does?

**Comment by busheezy** [comment]
Can this be looked into? It's one of the only things that is bugged with this skin.

**Comment by DirtDiglett** [comment]
I've fixed this for a 1.1 release.

I forgot to include a proper `selectedbg` declaration in some areas, so I'm also ensuring everywhere has this declared to avoid it occurring anywhere else as well.
