### ISSUE TITLE
Steam Windows are very slow and laggy

### ISSUE THREAD

**Issue by Soeren18** [DirtDiglett/Pressure2#93]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 Dark

#### Description of the issue.
The two skin variegated, run both very jerky. If I try to move the window of steam it is totally. Just like when I open the settings it takes 1-2 seconds until the window builds.

#### Does it also occur on Steam without the skin installed?
No, without the skin is not so and with other skins also not.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I am not in the Steam Beta.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10 Home Premium 64x

#### Are you using the latest stable release or using the latest commit version?
The versions come out when you press the big download button on their homepage.

#### A screenshot of the issue.
I can not photographed lags

#### Steps to reproduce the issue.
Skin and move the Steam window or open the settings.

**Comment by Abchrisabc** [comment]
I can confirm this as well, I also have these lag issues, I am part of the BETA. I am also using Dark, have tested this with the latest light version as well, the same issue occurs.

**Comment by CoWinkKeyDinkInc** [comment]
I have this issue on macOS as well.  Maybe it's because of the fonts?

**Comment by Soeren18** [comment]
Maybe, it is the font.
or
I think the problem is an edge smoothing which he uses or because there are any shadows with built in to make everything rounder, but the computer does not quite clear. Since it then runs over the CPU and not over the GPU.
Sry. but my english is very bad 😄 I am a german guy who is using the google translator 😹

**Comment by Alkaris** [comment]
Issue when using Steam overlay everything is slow loading the steam client's built-in browser when using this theme, the browser itself is just showing blank white screen boxes and can't load the web browser when activating the Steam overlay. Very annoying.

**Comment by DirtDiglett** [comment]
Yeah, this has been a longstanding issue that seems to affect some people randomly. Never found a root cause and all of the previous bugs that have caused performance issues that I solved over the years haven't solved it.

Can't do nothing about it sorry.
