### ISSUE TITLE
Overlapping text in Updating Games Play Window

### ISSUE THREAD

**Issue by goofolph** [DirtDiglett/Pressure2#99]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure2 master branch.

#### Description of the issue.
While updating a game pressing the play button opens a windows showing time remaining to update the game. The text should say "Ready to launch in approximately:" but is overlapping with the game's name.

#### Does it also occur on Steam without the skin installed?
No it does not.

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I am in the beta, it doesn't occur when opted out.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10 Pro 64-bit.

#### Are you using the latest stable release or using the latest commit version?
Latest commit in master.

Note: it does not occur with stable release 1.0.4.

#### A screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/2666631/26665180/b2daf07e-4665-11e7-918c-1a6e94a497c1.png)

#### Steps to reproduce the issue.
Start updating or installing game. From the library or downloads screen play the game. Windows pops up and text always overlaps for all games while in Steam beta.

**Comment by Dave247** [comment]
This issue was moved to Dave247/Pressure2#8

**Comment by Dave247** [comment]
The last few commits before 1.0.4 were from me so it must of been something I unintentionally did while trying to fix other issue. I'll look into it and see what I can find.

**Comment by Dave247** [comment]
However it broke, It's now fixed and hopefully won't break again.
